# Generated by Django 5.1.5 on 2025-02-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('input_type', models.CharField(choices=[('mic', 'Microphone'), ('file', 'File')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_type', models.CharField(choices=[('frequency', 'Frequency Priority'), ('amplitude', 'Amplitude Priority'), ('tone', 'Tone Priority'), ('both', 'Both Frequency & Amplitude')], max_length=20)),
                ('available', models.BooleanField(default=False)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='myApp.algorithm')),
            ],
        ),
    ]
