# Generated by Django 5.1.5 on 2025-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='input_type',
        ),
        migrations.AddField(
            model_name='algorithmvariation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='algorithm_files/'),
        ),
        migrations.AddField(
            model_name='algorithmvariation',
            name='input_type',
            field=models.CharField(choices=[('mic', 'Microphone Input'), ('file', 'File Input')], default='mic', max_length=10),
        ),
    ]
