# Generated by Django 5.1.5 on 2025-03-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_algorithm_input_type_algorithmvariation_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmvariation',
            name='input_type',
        ),
    ]
