# Generated by Django 5.1.5 on 2025-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_algorithmvariation_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmvariation',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
