# Generated by Django 5.1.5 on 2025-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_algorithmvariation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmvariation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/algorithm_files/'),
        ),
    ]
